/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AssetOriginTypes = {
    External: 'EXTERNAL',
    S3: 'S3'
} as const;
export type AssetOriginTypes = typeof AssetOriginTypes[keyof typeof AssetOriginTypes];


export function AssetOriginTypesFromJSON(json: any): AssetOriginTypes {
    return AssetOriginTypesFromJSONTyped(json, false);
}

export function AssetOriginTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetOriginTypes {
    return json as AssetOriginTypes;
}

export function AssetOriginTypesToJSON(value?: AssetOriginTypes | null): any {
    return value as any;
}

