/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DamAssetType = {
    Unknown: 'UNKNOWN',
    Image: 'IMAGE',
    Video: 'VIDEO',
    VideoExternal: 'VIDEO_EXTERNAL',
    Application: 'APPLICATION'
} as const;
export type DamAssetType = typeof DamAssetType[keyof typeof DamAssetType];


export function DamAssetTypeFromJSON(json: any): DamAssetType {
    return DamAssetTypeFromJSONTyped(json, false);
}

export function DamAssetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DamAssetType {
    return json as DamAssetType;
}

export function DamAssetTypeToJSON(value?: DamAssetType | null): any {
    return value as any;
}

