/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DamAsset
 */
export interface DamAsset {
    /**
     * 
     * @type {Date}
     * @memberof DamAsset
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DamAsset
     */
    'updatedAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof DamAsset
     */
    'id'?: string;
    /**
     * 
     * @type {DamAssetType}
     * @memberof DamAsset
     */
    'type'?: DamAssetType;
    /**
     * 
     * @type {string}
     * @memberof DamAsset
     */
    'code'?: string;
    /**
     * 
     * @type {Array<AssetMetadata>}
     * @memberof DamAsset
     */
    'metadata'?: Array<AssetMetadata>;
    /**
     * 
     * @type {string}
     * @memberof DamAsset
     */
    'grn'?: string;
    /**
     * 
     * @type {string}
     * @memberof DamAsset
     */
    'publicUrl'?: string;
}
