/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DamBatchUploadAssetsRequest
 */
export interface DamBatchUploadAssetsRequest {
    /**
     * 
     * @type {string}
     * @memberof DamBatchUploadAssetsRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {Array<BatchUploadAssetsRequestFiles>}
     * @memberof DamBatchUploadAssetsRequest
     */
    'files': Array<BatchUploadAssetsRequestFiles>;
}
