/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DamUpdateAssetRequest
 */
export interface DamUpdateAssetRequest {
    /**
     * 
     * @type {string}
     * @memberof DamUpdateAssetRequest
     */
    'tenantId': string;
    /**
     * 
     * @type {string}
     * @memberof DamUpdateAssetRequest
     */
    'id': string;
    /**
     * 
     * @type {UpdateAssetRequestPayload}
     * @memberof DamUpdateAssetRequest
     */
    'payload'?: UpdateAssetRequestPayload;
    /**
     * 
     * @type {string}
     * @memberof DamUpdateAssetRequest
     */
    'payloadMask'?: string;
}
