/* tslint:disable */
/* eslint-disable */
/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface UpdateAssetRequestPayload
 */
export interface UpdateAssetRequestPayload {
    /**
     * 
     * @type {string}
     * @memberof UpdateAssetRequestPayload
     */
    'code'?: string;
    /**
     * 
     * @type {DamAssetOrigin}
     * @memberof UpdateAssetRequestPayload
     */
    'origin': DamAssetOrigin;
    /**
     * 
     * @type {Array<AssetMetadata>}
     * @memberof UpdateAssetRequestPayload
     */
    'metadata'?: Array<AssetMetadata>;
}
