/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetMetadata } from '../models/AssetMetadata';
import { DamAssetType } from '../models/DamAssetType';
import { HttpFile } from '../http/http';

export class DamAsset {
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'id'?: string;
    'type'?: DamAssetType;
    'code'?: string;
    'metadata'?: Array<AssetMetadata>;
    'grn'?: string;
    'publicUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DamAssetType",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<AssetMetadata>",
            "format": ""
        },
        {
            "name": "grn",
            "baseName": "grn",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicUrl",
            "baseName": "publicUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DamAsset.attributeTypeMap;
    }

    public constructor() {
    }
}



