/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum DamAssetType {
    Unknown = 'UNKNOWN',
    Image = 'IMAGE',
    Video = 'VIDEO',
    VideoExternal = 'VIDEO_EXTERNAL',
    Application = 'APPLICATION'
}
