/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetOriginTypes } from '../models/AssetOriginTypes';
import { HttpFile } from '../http/http';

export class DamAssetOrigin {
    'url'?: string;
    'type'?: AssetOriginTypes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AssetOriginTypes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DamAssetOrigin.attributeTypeMap;
    }

    public constructor() {
    }
}



