/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchUploadAssetsRequestFiles } from '../models/BatchUploadAssetsRequestFiles';
import { HttpFile } from '../http/http';

export class DamBatchUploadAssetsRequest {
    'tenantId': string;
    'files': Array<BatchUploadAssetsRequestFiles>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<BatchUploadAssetsRequestFiles>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DamBatchUploadAssetsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

