/**
 * Dam Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DamListAssetsRequest {
    'tenantId': string;
    /**
    * The maximum number of assets to return. The service may return fewer than this value. If unspecified, at most 10 assets will be returned. The maximum value is 100; values above 100 will be coerced to 100.
    */
    'pageSize'?: number;
    /**
    * A page token, received from a previous `ListAssets` call. Provide this to retrieve the subsequent page.   When paginating, all other parameters provided to `ListAssets` must match the call that provided the page token.
    */
    'pageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pageToken",
            "baseName": "pageToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DamListAssetsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

